<?php

use Illuminate\Database\Seeder;

class PeliculaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('peliculas')->insert(['nombre' => 'Sangra. Grita. Late!', 'duracion_horas' => '1', 'duracion_minutos' => '40', 'sinopsis' => 'Juan, un profesor triste y apático trabaja en el mismo colegio donde fue víctima de bullying. Juan es el profesor favorito de Agustín, hijo de Pedro, su agresor, y Maribel, la chica de la que siempre estuvo enamorado. Ahora Agustín es víctima de ataques de sus compañeros, por lo que Pedro y Maribel están desesperados. Juan y Agustín han creado un lazo muy fuerte, se entienden y deciden que tienen que hacer algo para cambiar la situación en la que viven. Lejos de la desgracia, Santiago, un hombre de negocios, conoce a Eva y a Diana en una discoteca.', 'pais_id' => '228', 'pais_nombre' => 'U.S.A', 'imagen' => 'https://cineplanetstatic.azureedge.net/CDN/media/entity/get/FilmPosterGraphic/HO00000137?referenceScheme=HeadOffice&allowPlaceHolder=true', 'idioma_id' => '1', 'idioma_codigo' => 'EN', 'censura_id' => '1', 'censura_nombre' => 'APT', 'conpania_id' => '1', 'conpania_nombre' => 'Warnes Bross', 'ranking' => '7', 'popularidad' => '200', 'voto' => '590']);
        DB::table('peliculas')->insert(['nombre' => 'Megalodón', 'duracion_horas' => '2', 'duracion_minutos' => '0', 'sinopsis' => 'Cuando un sumergible se avería en pleno fondo marino del foso de las Marianas, un experto buceador arriesgará su vida en intentar el rescate, mientras le surge una duda: ¿existe todavía allá abajo el Megalodón, el predador marino más temible que ha existido nunca?', 'pais_id' => '228', 'pais_nombre' => 'U.S.A', 'imagen' => 'https://cineplanetstatic.azureedge.net/CDN/media/entity/get/FilmPosterGraphic/HO00000186?referenceScheme=HeadOffice&allowPlaceHolder=true', 'idioma_id' => '1', 'idioma_codigo' => 'EN', 'censura_id' => '1', 'censura_nombre' => '+14', 'conpania_id' => '1', 'conpania_nombre' => 'Universal Studios', 'ranking' => '10', 'popularidad' => '80', 'voto' => '600']);
        DB::table('peliculas')->insert(['nombre' => 'Christopher Robin Un reencuentro Inolvidable', 'duracion_horas' => '1', 'duracion_minutos' => '50', 'sinopsis' => 'El niño que se embarcó en innumerables aventuras en el bosque de los Cien Acres con su banda de animales de peluche, ha crecido y… ha perdido el rumbo. Ahora les toca a sus amigos de la infancia aventurarse en nuestro mundo y ayudar a Christopher Robin a recordar al niño cariñoso y juguetón que aún tiene dentro.', 'pais_id' => '228', 'pais_nombre' => 'U.S.A', 'imagen' => 'https://cineplanetstatic.azureedge.net/CDN/media/entity/get/FilmPosterGraphic/HO00000215?referenceScheme=HeadOffice&allowPlaceHolder=true', 'idioma_id' => '1', 'idioma_codigo' => 'EN', 'censura_id' => '1', 'censura_nombre' => 'APT', 'conpania_id' => '1', 'conpania_nombre' => 'Universal Studios', 'ranking' => '5', 'popularidad' => '20', 'voto' => '300']);
        DB::table('peliculas')->insert(['nombre' => '12 Horas para sobrevivir', 'duracion_horas' => '1', 'duracion_minutos' => '40', 'sinopsis' => 'Precuela de la franquicia "The Purge", que se centrará en los eventos que llevaron a la primera de todas las purgas anuales.', 'pais_id' => '228', 'pais_nombre' => 'U.S.A', 'imagen' => 'https://cineplanetstatic.azureedge.net/CDN/media/entity/get/FilmPosterGraphic/HO00000220?referenceScheme=HeadOffice&allowPlaceHolder=true', 'idioma_id' => '1', 'idioma_codigo' => 'EN', 'censura_id' => '1', 'censura_nombre' => 'APT', 'conpania_id' => '5', 'conpania_nombre' => 'Sony Pictures', 'ranking' => '2', 'popularidad' => '50', 'voto' => '100']);
        DB::table('peliculas')->insert(['nombre' => 'La Pequeña Brujita', 'duracion_horas' => '1', 'duracion_minutos' => '50', 'sinopsis' => 'La pequeña bruja sólo tiene 127 años, y es demasiado joven para poder acudir a la asamblea nacional de brujas. Además ella quiere no sólo ser simplemente una bruja, sino una muy buena. Esta decisión la traerá más de un problema en su mundo mágico.', 'pais_id' => '228', 'pais_nombre' => 'U.S.A', 'imagen' => 'https://cineplanetstatic.azureedge.net/CDN/media/entity/get/FilmPosterGraphic/HO00000225?referenceScheme=HeadOffice&allowPlaceHolder=true', 'idioma_id' => '1', 'idioma_codigo' => 'EN', 'censura_id' => '1', 'censura_nombre' => 'APT', 'conpania_id' => '5', 'conpania_nombre' => 'Sony Pictures', 'ranking' => '2', 'popularidad' => '56', 'voto' => '2000']);
        DB::table('peliculas')->insert(['nombre' => 'A la deriva', 'duracion_horas' => '1', 'duracion_minutos' => '40', 'sinopsis' => 'Basada en una historia real, narra cómo la pareja formada por los jóvenes Tami Oldham (Shailene Woodley) y su novio Richard (Sam Claflin) se hace a la mar en su velero, pero en medio del océano se ven sorprendidos por una de las mayores tormentas jamás registradas.', 'pais_id' => '228', 'pais_nombre' => 'U.S.A', 'imagen' => 'https://cineplanetstatic.azureedge.net/CDN/media/entity/get/FilmPosterGraphic/HO00000236?referenceScheme=HeadOffice&allowPlaceHolder=truhttps://aquipelis.tv/wp-content/uploads/2018/08/MV5BZDdjOWMwNjYtNWE3Zi00Y2JjLTgzODItNTg1YjNjM2U3ZWMyXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_SX300-160x230.jphttps://cineplanetstatic.azureedge.net/CDN/media/entity/get/FilmPosterGraphic/HO00000236?referenceScheme=HeadOffice&allowPlaceHolder=trueg', 'idioma_id' => '1', 'idioma_codigo' => 'EN', 'censura_id' => '2', 'censura_nombre' => '+14', 'conpania_id' => '1', 'conpania_nombre' => 'Warnes Bross', 'ranking' => '10', 'popularidad' => '50', 'voto' => '6000']);

    }
}
